# Generated by Django 4.0 on 2023-01-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_email_verified_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
