version: "3.9"
services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   volumes:
  #     - ./frontend/src:/app/src
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   command: npm start

  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: django_app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # command: "python manage.py runserver 0.0.0.0:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:


  ## for channel layers
  # redis_layer:
  #   image: redis
  #   container_name: redis_layer
  #   ports:
  #     - "6379:6379"
  # # for cache storage
  # redis_cache:
  #   image: redis
  #   container_name: redis_cache
  #   ports:
  #     - "6380:6380"
