version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_app
    # volumes:
    #   - ./frontend/src:/app/src
    volumes:
      - react_build:/frontend/build
    # ports:
    #   - 3000:3000
    # command: npm start

  django:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    container_name: django_app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod

    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pgdb

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - django
      - frontend
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
    pgdata:
    react_build:
