# Generated by Django 4.0 on 2023-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_counter',
            field=models.TextField(blank=True, default='No description', max_length=500, null=True, verbose_name='car counter'),
        ),
    ]
