# Generated by Django 4.0 on 2023-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_alter_caractivity_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caractivity",
            name="driver",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="the driver"),
        ),
    ]
