# Generated by Django 4.0 on 2023-01-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeactivity",
            name="phase_out",
            field=models.TimeField(blank=True, null=True, verbose_name="employee phase out time"),
        ),
    ]
