# Generated by Django 4.0 on 2023-01-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("store", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees_created",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="insurance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to="employee.insurance",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="employeeactivity",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="employee.employee"
            ),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insurances_created",
                to="account.account",
            ),
        ),
    ]
