# Generated by Django 4.0 on 2023-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(choices=[('مهندس', 'مهندس'), ('سائق', 'سائق')], default='Please pick employee category', max_length=20, verbose_name='Employee Category'),
        ),
    ]
