# Generated by Django 4.0 on 2023-01-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ("-created_at",), "verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
    ]
