# Generated by Django 4.0 on 2023-01-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=250, unique=True, verbose_name="employee name"),
        ),
    ]
