# Generated by Django 4.0 on 2023-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employeeactivity_phase_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=250, verbose_name="employee name"),
        ),
    ]
