# Generated by Django 4.0 on 2023-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_employee_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_category",
            field=models.CharField(
                choices=[
                    (None, "(Unknown)"),
                    ("EN", "Enginner"),
                    ("DR", "Driver"),
                    ("AC", "Acounter"),
                    ("SP", "Supervisor"),
                    ("HR", "Human Resource"),
                    ("MG", "Manager"),
                    ("EM", "Employee"),
                ],
                default="EM",
                max_length=25,
                verbose_name="employee category",
            ),
        ),
    ]
