# Generated by Django 4.0 on 2023-03-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_employee_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_category",
            field=models.CharField(
                choices=[
                    (None, "(Unknown)"),
                    ("ENGINNER", "Enginner"),
                    ("DRIVER", "Driver"),
                    ("ACOUNTER", "Acounter"),
                    ("SUPERVISOR", "Supervisor"),
                    ("HUMAN_RESOURCE", "Human Resource"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Employee"),
                ],
                default="(Unknown)",
                max_length=25,
                verbose_name="employee category",
            ),
        ),
    ]
