# Generated by Django 4.0 on 2023-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_employee_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="ins_code",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name="Insurance code"),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="ins_company",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Insurance issued company"),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="ins_type",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Insurance type"),
        ),
    ]
