# Generated by Django 4.0 on 2023-01-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ("-media_pack__created_at",),
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["-created_at"], "verbose_name": "Store", "verbose_name_plural": "Stores"},
        ),
    ]
