# Generated by Django 4.0 on 2023-01-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("substance", "0003_remove_invoiceinstrumentitem_instrument_and_more"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSubstanceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mass", models.BigIntegerField(verbose_name="invoice substance mass")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="No description",
                        max_length=500,
                        null=True,
                        verbose_name="invoice substance information",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_items",
                        to="substance.substance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceInstrumentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="No description",
                        max_length=500,
                        null=True,
                        verbose_name="invoice instrument information",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_items",
                        to="substance.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, null=True, verbose_name="invoice note")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to="account.account",
                    ),
                ),
                ("instruments", models.ManyToManyField(related_name="invoice", to="store.InvoiceInstrumentItem")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="store.store"
                    ),
                ),
                ("substances", models.ManyToManyField(related_name="invoice", to="store.InvoiceSubstanceItem")),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
    ]
