# Generated by Django 4.0 on 2023-01-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="media_pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.mediapack"
            ),
        ),
        migrations.AlterField(
            model_name="mediapack",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mediapacks_created",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="mediapack",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="mediapacks", to="store.store"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores_created",
                to="account.account",
            ),
        ),
    ]
