# Generated by Django 4.0 on 2023-01-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("store", "0002_alter_image_media_pack_alter_mediapack_created_by_and_more"),
        ("substance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrument",
            name="ins_type",
        ),
        migrations.AlterField(
            model_name="instrument",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="instruments", to="substance.Category", verbose_name="instrumen Category"
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instruments_created",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_created",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="instruments",
            field=models.ManyToManyField(related_name="invoice", to="substance.InvoiceInstrumentItem"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="store.store"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="substances",
            field=models.ManyToManyField(related_name="invoice", to="substance.InvoiceSubstanceItem"),
        ),
        migrations.AlterField(
            model_name="invoiceinstrumentitem",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices_items",
                to="substance.instrument",
            ),
        ),
        migrations.AlterField(
            model_name="invoicesubstanceitem",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices_items",
                to="substance.substance",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="substances", to="substance.Category", verbose_name="substance Category"
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances_created",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="unit_type",
            field=models.CharField(
                choices=[("kilogram", "kilogram"), ("liter", "liter"), ("ton", "ton")],
                max_length=20,
                verbose_name="Unit Type",
            ),
        ),
    ]
