# Generated by Django 4.0 on 2023-01-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ("-created_at",), "verbose_name": "Instrument", "verbose_name_plural": "Instruments"},
        ),
        migrations.AlterModelOptions(
            name="substance",
            options={"ordering": ("-created_at",), "verbose_name": "Substance", "verbose_name_plural": "Substances"},
        ),
    ]
