# Generated by Django 4.0 on 2023-01-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="invoice note"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="instruments",
            field=models.ManyToManyField(through="substance.InvoiceInstrumentItem", to="substance.Instrument"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="substances",
            field=models.ManyToManyField(through="substance.InvoiceSubstanceItem", to="substance.Substance"),
        ),
        migrations.AlterField(
            model_name="invoiceinstrumentitem",
            name="instrument",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="substance.instrument"
            ),
        ),
        migrations.AlterField(
            model_name="invoicesubstanceitem",
            name="mass",
            field=models.BigIntegerField(verbose_name="invoice substance mass"),
        ),
        migrations.AlterField(
            model_name="invoicesubstanceitem",
            name="substance",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="substance.substance"
            ),
        ),
    ]
