# Generated by Django 4.0 on 2023-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0002_alter_instrument_category_alter_substance_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="instrument_categories",
                to="substance.Category",
                verbose_name="instrumen Category",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="substance_categories",
                to="substance.Category",
                verbose_name="substance Category",
            ),
        ),
    ]
