# Generated by Django 4.0 on 2023-01-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0002_alter_instrument_options_alter_substance_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceinstrumentitem",
            name="instrument",
        ),
        migrations.RemoveField(
            model_name="invoicesubstanceitem",
            name="substance",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceInstrumentItem",
        ),
        migrations.DeleteModel(
            name="InvoiceSubstanceItem",
        ),
    ]
