# Generated by Django 4.0 on 2023-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0002_alter_substance_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substance",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("KG", "kilogram"),
                    ("L", "letter"),
                    ("T", "ton"),
                    ("M", "meter"),
                    ("M_2", "square meter"),
                    ("M_3", "cubic meter"),
                    ("DAHAN", "dahan"),
                    ("SH_20", "shakara 20"),
                    ("SH_25", "shakara 25"),
                    ("SH_50", "shakara 50"),
                    ("SH_M", "shakara paste"),
                    ("PIECE", "piece"),
                ],
                max_length=20,
                verbose_name="Unit Type",
            ),
        ),
    ]
