# Generated by Django 4.0 on 2023-01-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substance', '0002_alter_substance_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='unit_type',
            field=models.CharField(choices=[('كيلوجرام', 'كيلوجرام'), ('لتر', 'لتر'), ('طن', 'طن'), ('متر طولي', 'متر طولي'), ('متر مربع', 'متر مربع'), ('متر مكعب', 'متر مكعب'), ('دهان', 'دهان'), ('شكارة 20', 'شكارة 20'), ('شكارة 25', 'شكارة 25'), ('شكارة 50', 'شكارة 50'), ('شكارة معجون', 'شكارة معجون'), ('قطعة', 'قطعة')], max_length=20, verbose_name='Unit Type'),
        ),
    ]
