# Generated by Django 4.0 on 2023-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0004_alter_substance_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substance",
            name="unit_type",
            field=models.CharField(
                choices=[
                    (None, "(Unknown)"),
                    ("KG", "Kilogram"),
                    ("L", "Letter"),
                    ("T", "Ton"),
                    ("M", "Meter"),
                    ("M_2", "Square meter"),
                    ("M_3", "Cubic meter"),
                    ("DAHAN", "Dahan"),
                    ("SH_20", "Shakara 20"),
                    ("SH_25", "Shakara 25"),
                    ("SH_50", "Shakara 50"),
                    ("SH_M", "Shakara paste"),
                    ("PIECE", "Piece"),
                ],
                default="KG",
                max_length=25,
            ),
        ),
    ]
