# Generated by Django 4.0 on 2023-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("substance", "0005_alter_substance_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substance",
            name="unit_type",
            field=models.CharField(
                choices=[
                    (None, "(Unknown)"),
                    ("KILOGRAM", "Kilogram"),
                    ("LETTER", "Letter"),
                    ("TON", "Ton"),
                    ("METER", "Meter"),
                    ("SQUARE_METER", "Square meter"),
                    ("CUBIC_METER", "Cubic meter"),
                    ("DAHAN", "Dahan"),
                    ("SHAKARA_20", "Shakara 20"),
                    ("SHAKARA_25", "Shakara 25"),
                    ("SHAKARA_50", "Shakara 50"),
                    ("SHAKARA_PASTE", "Shakara paste"),
                    ("PIECE", "Piece"),
                ],
                default="KILOGRAM",
                max_length=25,
            ),
        ),
    ]
