# Generated by Django 4.0 on 2023-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="note",
            field=models.TextField(
                blank=True, default="No description", max_length=500, null=True, verbose_name="car note"
            ),
        ),
    ]
